<?php

namespace NextDeveloper\Events\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

/**
 * Generates the NATS authorization config file from the database.
 *
 * The generated file is included by nats.conf via:
 *   include "/etc/nats/nats_auth.conf"
 *
 * After writing, send SIGHUP to NATS to hot-reload:
 *   docker compose kill -s HUP nats
 */
class NatsAuthConfigService
{
    public function generate(): string
    {
        $lines   = [];
        $lines[] = '# nats_auth.conf — auto-generated by NatsAuthConfigService';
        $lines[] = '# Do not edit manually. Run: php artisan events:nats-generate-auth';
        $lines[] = '';
        $lines[] = 'authorization {';
        $lines[] = '  users: [';

        // Platform — Laravel internal connections (full access)
        $platformToken = config('events.nats.token') ?? config('events.nats.password');
        if ($platformToken) {
            $lines[] = '    # Laravel platform';
            $lines[] = '    {';
            $lines[] = '      user: "platform"';
            $lines[] = '      password: "' . addslashes($platformToken) . '"';
            $lines[] = '      permissions: {';
            $lines[] = '        publish:   { allow: [">"] }';
            $lines[] = '        subscribe: { allow: [">"] }';
            $lines[] = '      }';
            $lines[] = '    }';
        }

        // Compute agents - dedicated agent_api_key, separate from events_token
        // (which stays scoped to the older XenServer SSH-webhook mechanism)
        $this->appendAgentUsers($lines, 'iaas_compute_members', 'compute', 'agent_api_key');

        // Storage agents
        $this->appendAgentUsers($lines, 'iaas_storage_members', 'storage');

        // Network agents
        $this->appendAgentUsers($lines, 'iaas_network_members', 'network');

        $lines[] = '  ]';
        $lines[] = '}';

        return implode("\n", $lines) . "\n";
    }

    public function write(): void
    {
        $path    = config('events.nats.auth_config_path', '/etc/nats/nats_auth.conf');
        $content = $this->generate();

        file_put_contents($path, $content);

        Log::info('[NatsAuthConfigService] Auth config written', ['path' => $path]);
    }

    public function reload(): void
    {
        $command = config('events.nats.reload_command', 'docker compose kill -s HUP nats');

        exec($command, $output, $code);

        if ($code !== 0) {
            Log::error('[NatsAuthConfigService] NATS reload failed', [
                'command' => $command,
                'output'  => implode("\n", $output),
                'code'    => $code,
            ]);
            return;
        }

        Log::info('[NatsAuthConfigService] NATS reloaded successfully');
    }

    // -------------------------------------------------------------------------

    private function appendAgentUsers(array &$lines, string $table, string $type, string $credentialColumn = 'events_token'): void
    {
        // Skip if the table doesn't have the credential column
        if (!$this->tableHasColumn($table, $credentialColumn)) {
            return;
        }

        $agents = DB::table($table)
            ->whereNotNull($credentialColumn)
            ->whereNull('deleted_at')
            ->select(['uuid', $credentialColumn])
            ->get();

        if ($agents->isEmpty()) {
            return;
        }

        $lines[] = '';
        $lines[] = "    # {$type} agents ({$agents->count()})";

        foreach ($agents as $agent) {
            $lines[] = '    {';
            $lines[] = '      user: "' . $type . '-' . $agent->uuid . '"';
            $lines[] = '      password: "' . addslashes($agent->{$credentialColumn}) . '"';
            $lines[] = '      permissions: {';
            $lines[] = '        subscribe: { allow: [';
            $lines[] = '          "agent.' . $type . '.' . $agent->uuid . '.cmd"';
            $lines[] = '          "agent.' . $type . '.broadcast"';
            $lines[] = '          "agent.broadcast"';
            $lines[] = '        ] }';
            $lines[] = '        publish: { allow: [';
            $lines[] = '          "agent.' . $type . '.' . $agent->uuid . '.evt"';
            $lines[] = '        ] }';
            $lines[] = '      }';
            $lines[] = '    }';
        }
    }

    private function tableHasColumn(string $table, string $column): bool
    {
        try {
            $columns = DB::getSchemaBuilder()->getColumnListing($table);
            return in_array($column, $columns, true);
        } catch (\Throwable) {
            return false;
        }
    }
}
